# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Alex\Competitions_TT\UI\protocol_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProtocolForm(object):
    def setupUi(self, ProtocolForm):
        ProtocolForm.setObjectName("ProtocolForm")
        ProtocolForm.resize(794, 1123)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ProtocolForm.sizePolicy().hasHeightForWidth())
        ProtocolForm.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProtocolForm)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(ProtocolForm)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 774, 2200))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.protocol_1 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.protocol_1.setMinimumSize(QtCore.QSize(0, 500))
        self.protocol_1.setFrameShape(QtWidgets.QFrame.Box)
        self.protocol_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.protocol_1.setObjectName("protocol_1")
        self.layout_protocol_1 = QtWidgets.QVBoxLayout(self.protocol_1)
        self.layout_protocol_1.setContentsMargins(10, 10, 10, 10)
        self.layout_protocol_1.setSpacing(5)
        self.layout_protocol_1.setObjectName("layout_protocol_1")
        self.verticalLayout_2.addWidget(self.protocol_1)
        self.protocol_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.protocol_2.setMinimumSize(QtCore.QSize(0, 500))
        self.protocol_2.setFrameShape(QtWidgets.QFrame.Box)
        self.protocol_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.protocol_2.setObjectName("protocol_2")
        self.layout_protocol_2 = QtWidgets.QVBoxLayout(self.protocol_2)
        self.layout_protocol_2.setContentsMargins(10, 10, 10, 10)
        self.layout_protocol_2.setSpacing(5)
        self.layout_protocol_2.setObjectName("layout_protocol_2")
        self.verticalLayout_2.addWidget(self.protocol_2)
        self.protocol_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.protocol_3.setMinimumSize(QtCore.QSize(0, 500))
        self.protocol_3.setFrameShape(QtWidgets.QFrame.Box)
        self.protocol_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.protocol_3.setObjectName("protocol_3")
        self.layout_protocol_3 = QtWidgets.QVBoxLayout(self.protocol_3)
        self.layout_protocol_3.setContentsMargins(10, 10, 10, 10)
        self.layout_protocol_3.setSpacing(5)
        self.layout_protocol_3.setObjectName("layout_protocol_3")
        self.verticalLayout_2.addWidget(self.protocol_3)
        self.protocol_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.protocol_4.setMinimumSize(QtCore.QSize(0, 500))
        self.protocol_4.setFrameShape(QtWidgets.QFrame.Box)
        self.protocol_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.protocol_4.setObjectName("protocol_4")
        self.layout_protocol_4 = QtWidgets.QVBoxLayout(self.protocol_4)
        self.layout_protocol_4.setContentsMargins(10, 10, 10, 10)
        self.layout_protocol_4.setSpacing(5)
        self.layout_protocol_4.setObjectName("layout_protocol_4")
        self.verticalLayout_2.addWidget(self.protocol_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.btn_generate = QtWidgets.QPushButton(ProtocolForm)
        self.btn_generate.setObjectName("btn_generate")
        self.verticalLayout.addWidget(self.btn_generate)

        self.retranslateUi(ProtocolForm)
        QtCore.QMetaObject.connectSlotsByName(ProtocolForm)

    def retranslateUi(self, ProtocolForm):
        _translate = QtCore.QCoreApplication.translate
        ProtocolForm.setWindowTitle(_translate("ProtocolForm", "Протокол командного матча"))
        self.btn_generate.setText(_translate("ProtocolForm", "Создать протоколы"))
